### ISSUE TITLE
Add a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by AdithyaBhat17** [AdithyaBhat17/interview-cookbook#10]
Add a markdown file with instructions for adding questions+solutions, updating the README file and sending a PR.

**Comment by wagnernegrao** [comment]
Hi, 

Can I make this?

**Comment by AdithyaBhat17** [comment]
Hey! Sure, go ahead!!

And thanks in advance!! :smile:

**Comment by wagnernegrao** [comment]
Concluded in PR #20
